os:
  - linux
  - osx

sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
    - wine

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wine; fi

install:
  - npm i -g npm
  - npm install

script:
  - npm run compile
  - npm run test
