env:
  - NODE_VERSION="5.8"

os:
  - linux
  - osx

before_install: ./script/travis-preinstall.sh

install:
  - node --version
  - npm --version
  - npm install

script: npm test

cache:
  directories:
    - node_modules

notifications:
  email: false
